### ISSUE TITLE
I can see a list of all sports

### ISSUE THREAD

**Issue by Kevinwey** [Kevinwey/capstone_sport-synergie#1]
### **Value Proposition**
<hr>

**As a** User
**I want to** see a list of all sports
**so that** I have an overview of all sports

### **Description**
<hr>

![Image](https://user-images.githubusercontent.com/123939438/229360952-52366592-4ab4-47aa-81e4-2e5fa5e178e8.png)

### **Acceptance Criteria**
<hr>

- [x] all sports are displayed in a list
- [x] the list should have a headline
- [x] sorted by name

### **Tasks**
<hr>

- [x] create dummy data
- [x] fetch the dummy data and displayed it in a list
- [x] write tests
