### ISSUE TITLE
I can choose my sport

### ISSUE THREAD

**Issue by Kevinwey** [Kevinwey/capstone_sport-synergie#14]
### **Value Proposition**
<hr>

**As a** User
**I want to** have the ability to select my preferred sport
**so that** I can easily view and focus on the sports that interest me the most

### **Description**
<hr>

![Image](https://user-images.githubusercontent.com/123939438/230767130-537b31c8-34f8-4244-8a53-5b9432513750.png)

### **Acceptance Criteria**
<hr>

- [x] the user can choose one sport on the `SelectorPage`
- [x] a description is displayed under the sports if choose one on the `SelectorPage`
- [x] a newRoll Button is displayed on the `SelectorPage`
- [x] the chosen sport is displayed on the `ProfilePage`
- [x] the newRoll Button generates three new sports on the `SelectorPage`

### **Tasks**
<hr>

- [x] update sports.js 
- [x] update states

**Comment by ChristophObst** [comment]
LGTM
