### ISSUE TITLE
I can add my level of the current sport

### ISSUE THREAD

**Issue by Kevinwey** [Kevinwey/capstone_sport-synergie#17]
### **Value Proposition**
<hr>

**As a** User
**I want to** see my level of the current sport
**so that** I can set goals and evaluate my training strategies more easily

### **Description**
<hr>

![Image](https://user-images.githubusercontent.com/123939438/231105343-b3cf48dd-dd1c-41e4-84bc-c54c1d5e70f4.png)

### **Acceptance Criteria**
<hr>

- [x] the user can enter the `SportDetailsPage`
- [x] the sport is displayed on the `SportDetailsPage`
- [x] the user can choose between 3 levels
- [x] the user can enter the `SportDetailsPage` by clicking the sport on the `ProfilePage`

### **Tasks**
<hr>

**Comment by Satttoshi** [comment]
lgtm :rocket: 

A suggestion from my side: Instead of a dropdown menu, a visual section with a increment and decrement button might be a better choice here.
