### ISSUE TITLE
I can see my days invest in my sport

### ISSUE THREAD

**Issue by Kevinwey** [Kevinwey/capstone_sport-synergie#18]
### **Value Proposition**
<hr>

**As a** User
**I want to** track my progress for my sport
**so that** I can monitor my improvement over time

### **Description**
<hr>

![Image](https://user-images.githubusercontent.com/123939438/231397905-18e12d23-829a-440b-b931-b3e37986700e.png)

### **Acceptance Criteria**
<hr>

- [x] a GO! button is displayed on the `SportDetailsPage`
- [x] the GO! button changes to the days invest if clicked 
- [x] the days invest are displayed on the `ProfilePage`
- [x] the level is displayed on the `ProfilePage`

### **Tasks**
<hr>

**Comment by AnjaSiewert** [comment]
LGTM, you could add the second wireframe for the profile page so the US is more clear :)
