### ISSUE TITLE
I can see a list of all my sports

### ISSUE THREAD

**Issue by Kevinwey** [Kevinwey/capstone_sport-synergie#21]
### **Value Proposition**
<hr>

**As a** User
**I want to** view my progress in individual sports and the associated days invested
**so that** I can swiftly assess my achievements comprehensively

### **Description**
<hr>

![Image](https://user-images.githubusercontent.com/123939438/231137600-5abd17e7-0726-46ac-a11c-a4d7d03c5f5d.png)

### **Acceptance Criteria**
<hr>

- [x] a  `Link` is displayed on the `ProfilePage` which leads to the `MySportsPage`
- [x] sport and the associated days invested are displayed on the `MySportsPage`
- [x] a back `Link` is displayed on the `MySportsPage` 

### **Tasks**
<hr>

**Comment by JessicaLoers** [comment]
**Well done @Kevinwey**  ✨

The back button (which should be a link by the way) that you mention in your AC is not visible on the wire frame. But there is a Profile button that is not mentioned. Maybe you can define this part more precisely and work it out.

**Furthermore there are just some very petty comments for you to think about.**

_A suggestion to formulate the value proposition a little more precisely:_
**As a User**
**I want to** view my progress in individual sports and the associated days invested
**so that I** can swiftly assess my achievements comprehensively

_Another suggestion 😁_
 - sport and  the **associated days invested are** displayed on the MySportsPage

**Comment by Kevinwey** [comment]
thank you, these tips help a lot 🚀

**Comment by toshydev** [comment]
The back `button` in the *acceptance criteria* should be a `link` e.g. for performance optimisation.
Rest LGTM! ✅
