### ISSUE TITLE
I can access the app

### ISSUE THREAD

**Issue by Kevinwey** [Kevinwey/capstone_sport-synergie#3]
### **Value Proposition**
<hr>

**As a** User
**I want to** see a clearly labeled button
**so that** I can access the app quickly and easily

### **Description**
<hr>

![Image](https://user-images.githubusercontent.com/123939438/229363018-da119e6a-f42f-4acb-89da-91e928619b73.png)

### **Acceptance Criteria**
<hr>

- [x] a "GO!" button is shown on the homepage
- [x] the button should lead to the list of sports

### **Tasks**
<hr>

- [ ] write a button component

**Comment by ChristophObst** [comment]
lgtm
