### ISSUE TITLE
I can access the app

### ISSUE THREAD

**Issue by Kevinwey** [Kevinwey/capstone_sport-synergie#6]
### **Value Proposition**
<hr>

**As a** User
**I want to** see a clearly labeled button on the homepage
**so that** I can access the app quickly and easily

### **Description**
<hr>

![Image](https://user-images.githubusercontent.com/123939438/229366165-e0967500-3bec-40c0-8f31-7fc4eae29050.png)

### **Acceptance Criteria**
<hr>

- [x] a button is displayed on the `HomePage`
- [x] the button leads to the `SelectorPage`

### **Tasks**
<hr>

- [x] write a Button component
