### ISSUE TITLE
I can see my profile

### ISSUE THREAD

**Issue by Kevinwey** [Kevinwey/capstone_sport-synergie#7]
### **Value Proposition**
<hr>

**As a** User
**I want to** see my profile
**so that** I have an overview about my progress

### **Description**
<hr>

![Image](https://user-images.githubusercontent.com/123939438/229366643-d7dcf859-be86-489a-adba-2349d074b128.png)

### **Acceptance Criteria**
<hr>

- [x] age, weight, height, sport and level are displayed on the `ProfilePage`
- [x] age, weight, height, sport and level are filled with dummy data
- [x] the data should have a headline

### **Tasks**
<hr>

**Comment by manukao** [comment]
lgtm 🏋🏻
