### ISSUE TITLE
I  have the ability to input my personal information

### ISSUE THREAD

**Issue by Kevinwey** [Kevinwey/capstone_sport-synergie#8]
### **Value Proposition**
<hr>

**As a** User
**I want to** have the ability to input my personal information
**so that** I can gain access to its features and functionality

### **Description**
<hr>

![Image](https://user-images.githubusercontent.com/123939438/229368039-b06a8a0c-8aac-4c61-b7ea-cd9054071757.png)

### **Acceptance Criteria**
<hr>

- [x] a form is displayed on the `FormPage`
- [x] a submit button is displayed on the `FormPage`
- [x] the submit button leads to the `SelectorPage`
- [x] the form resets after submitting the button
- [x] the data entered are on the `ProfilePage`

### **Tasks**
<hr>

**Comment by manukao** [comment]
just some inspiration, since "gain access to its features and functionality" sounds a bit generalistic

As a user
I want to provide my personal data to the app
so that I can get tailored recommendations for sports that would best fit me

**Comment by Kevinwey** [comment]
Good point! thanks :)
